# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               What Happens When?
tagline:             Seriously
url:                 http://what-happens-when.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              George
  url:               https://twitter.com/thehappyhapps
  email:             butwhatreallyhappens@gmail.com

# Custom vars
version:             0.0.1
github:
  repo:              https://github.com/what-happens-when/what-happens-when.github.io

gems:
  - jekyll-sitemap

markdown: rdiscount

rdiscount:
  extensions: ["autolink", "footnotes", "generate_toc", "smart"]
  toc_token: "[TOC]"